### ISSUE TITLE
Segmentation fault when using ydotool with ydotoold

### ISSUE THREAD

**Issue by touste** [ReimuNotMoe/ydotool#15]
On Arch with latest aur build I've got this issue when trying to use ydotool with the daemon. I also have updated libuinputplus to latest aur build.

 Starting the daemon itself works fine:
```
> sudo ydotoold
ydotoold: listening on socket /tmp/.ydotool_socket
ydotoold: accepted client
```

But then when trying ydotool in another terminal:
```
> sudo ydotool type 'test'
ydotool: library search path: /usr/local/lib/ydotool:/usr/lib/ydotool:/usr/lib/x86_64-linux-gnu/ydotool:/usr/lib/i386-linux-gnu/ydotool

ydotool: notice: Using ydotoold backend
ydotool: debug: tool `type' constructed at 0x5620997e4a10
argc = 2
argv[1] = test
Usage: ydotool <cmd> <args>
Available commands:
  mousemove
  type
  key
  click
zsh: segmentation fault  sudo ydotool type 'test'
```

Trying this in gdb I've got this backtrace:
```
Program received signal SIGSEGV, Segmentation fault.
0x0000000100140001 in ?? ()
(gdb) bt
#0  0x0000000100140001 in ?? ()
#1  0x89503bf2b6585900 in ?? ()
#2  0x00007fffffffe120 in ?? ()
#3  0x00007ffff7f98984 in uInputPlus::uInput::Emit(unsigned short, unsigned short, int) const () from /usr/lib/libuInputPlus.so.0
#4  0x00007ffff7f989ef in uInputPlus::uInput::SendKey(unsigned short, unsigned int, bool) const () from /usr/lib/libuInputPlus.so.0
#5  0x00007ffff794bb92 in Type::TypeText(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) () from /usr/lib/ydotool/libtype.so
#6  0x00007ffff794cc1e in Type::Exec(int, char const**) () from /usr/lib/ydotool/libtype.so
#7  0x0000555555557451 in main ()
```

ydotool without the daemon works fine.

**Comment by kitakar5525** [comment]
I made a PR #18. Should fix this issue.

**Comment by touste** [comment]
I can confirm that this fixed the issue for me, thanks!

**Comment by curiositry** [comment]
I am still getting the ydotoold segmentation fault described in Issue #15, which was appearantly fixed in PR #18. I am running Ubuntu 20.04. This happens regardless whether I use the static build for Ubuntu 19.10, or compile from source. Standalone `ydotool` works fine.

Is anyone else still getting the `ydotoold` segfault?

Thanks!

**Comment by scott092707** [comment]
I am using Sway 1.5 in Debian Testing (Bullseye?).  
Same here:
scott@ASUS-Prime-B350MA:~$ sudo ydotoold
ydotoold: listening on socket /tmp/.ydotool_socket
ydotoold: accepted client
Segmentation fault
scott@ASUS-Prime-B350MA:~$ 
-------------------------- when on other terminal --------------------------
scott@ASUS-Prime-B350MA:~$ sudo ydotool type "test"
ydotool: notice: Using ydotoold backend
scott@ASUS-Prime-B350MA:~$ 
------------------------------------------------------------------------------------
scott@ASUS-Prime-B350MA:~$ apt-cache policy ydotool ydotoold
ydotool:
  Installed: 0.1.8-2
  Candidate: 0.1.8-2
  Version table:
 *** 0.1.8-2 100
        100 /var/lib/dpkg/status
ydotoold:
  Installed: 0.1.8-2
  Candidate: 0.1.8-2
  Version table:
 *** 0.1.8-2 100
        100 /var/lib/dpkg/status

**Comment by williamd5** [comment]
getting this on ubuntu 22.04 lts
```
segmentation fault (core dumped)  ydotoold
```

**Comment by AlexanderHD27** [comment]
This Issue is still a problem. Waylands + Ubuntu KeyPress-emulation alternativis are very slim. It would be really nice if this gets fixed. I'm having the same issue btw. I'm running Wayland with gnome 42.5 on Ubuntu 22.04 LTS

**Comment by amig01** [comment]
> getting this on ubuntu 22.04 lts
> 
> ```
> segmentation fault (core dumped)  ydotoold
> ```

The same
